Q1.	Handle missing values as per the best practices (imputation, removal, etc.).
●	Apply scaling techniques to numerical features:
a.	Standard Scaling   b. Min-Max Scaling
●	Discuss the scenarios where each scaling technique is preferred and why.

In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\vinod\Downloads\Data Trasformation\adult_with_headers (1).csv")
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [6]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [8]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [16]:
scaler_std = StandardScaler()
df_std = df.copy()
df_std[num_cols] = scaler_std.fit_transform(df_std[num_cols])

print("\n===== STANDARD SCALED DATA =====")
print(df_std[num_cols].head())

===== STANDARD SCALED DATA =====
        age    fnlwgt  education_num  capital_gain  capital_loss  \
0  0.030671 -1.063611       1.134739      0.148453      -0.21666
1  0.837109 -1.008707       1.134739     -0.145920      -0.21666
2 -0.042642  0.245079      -0.420060     -0.145920      -0.21666
3  1.057047  0.425801      -1.197459     -0.145920      -0.21666
4 -0.775768  1.408176       1.134739     -0.145920      -0.21666

   hours_per_week
0       -0.035429
1       -2.222153
2       -0.035429
3       -0.035429
4       -0.035429

In [17]:
# Min-Max Scaling
scaler_mm = MinMaxScaler()
df_mm = df.copy()
df_mm[num_cols] = scaler_mm.fit_transform(df_mm[num_cols])

print("\n===== MIN-MAX SCALED DATA =====")
print(df_mm[num_cols].head())

===== MIN-MAX SCALED DATA =====
        age    fnlwgt  education_num  capital_gain  capital_loss  \
0  0.301370  0.044302       0.800000       0.02174           0.0
1  0.452055  0.048238       0.800000       0.00000           0.0
2  0.287671  0.138113       0.533333       0.00000           0.0
3  0.493151  0.151068       0.400000       0.00000           0.0
4  0.150685  0.221488       0.800000       0.00000           0.0

   hours_per_week
0        0.397959
1        0.122449
2        0.397959
3        0.397959
4        0.397959

Method:
 StandardScaler :Normal distribution, ML models (SVM, Logistic Regression) 
 MinMaxScaler   :Neural networks, bounded features

In [ ]:
Q2. Encoding Techniques:
●	Apply One-Hot Encoding to categorical variables with less than 5 categories.
●	Use Label Encoding for categorical variables. Data Exploration and Preprocessing:
●	Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).
●	les with more than 5 categories.
●	Discuss the pros and cons of One-Hot Encoding and Label Encoding.

In [10]:
from sklearn.preprocessing import LabelEncoder

cat_cols = df.select_dtypes(include=['object']).columns

le = LabelEncoder()

for col in cat_cols:
    if df[col].nunique() <= 5:
        df = pd.get_dummies(df, columns=[col])
    else:
        df[col] = le.fit_transform(df[col])

In [11]:
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,capital_gain,capital_loss,...,native_country,race_ Amer-Indian-Eskimo,race_ Asian-Pac-Islander,race_ Black,race_ Other,race_ White,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,39,7,77516,9,13,4,1,1,2174,0,...,39,False,False,False,False,True,False,True,True,False
1,50,6,83311,9,13,2,4,0,0,0,...,39,False,False,False,False,True,False,True,True,False
2,38,4,215646,11,9,0,6,1,0,0,...,39,False,False,False,False,True,False,True,True,False
3,53,4,234721,1,7,2,6,0,0,0,...,39,False,False,True,False,False,False,True,True,False
4,28,4,338409,9,13,2,10,5,0,0,...,5,False,False,True,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,4,257302,7,12,2,13,5,0,0,...,39,False,False,False,False,True,True,False,True,False
32557,40,4,154374,11,9,2,7,0,0,0,...,39,False,False,False,False,True,False,True,False,True
32558,58,4,151910,11,9,6,1,4,0,0,...,39,False,False,False,False,True,True,False,True,False
32559,22,4,201490,11,9,4,1,3,0,0,...,39,False,False,False,False,True,False,True,True,False
32560,52,5,287927,11,9,2,4,5,15024,0,...,39,False,False,False,False,True,True,False,False,True

one Hot Encoding :
pros: 1.No Order assumption
      2.Better for small categories 
cons:
*Columns increase 

Label Encoding :
pros : 1.Memory efficient
       2.Fast 
cons:
*order assume wrong

Q3. Feature Engineering:
●	Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.
●	Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

In [12]:
## New feature 1 : age group 
df['age_group'] = pd.cut(df['age'], bins=[0,25,50,100], labels=['Young','Adult','Old'])
# Reason: The model can capture patterns more effictively.

In [13]:
print(df[['age_group']].head(10))

  age_group
0     Adult
1     Adult
2     Adult
3       Old
4     Adult
5     Adult
6     Adult
7       Old
8     Adult
9     Adult

In [16]:
## New feature 2 : Hours Category 
df['hours_category'] = pd.cut(df['hours_per_week'], bins=[0,25,40,100], labels=['Part-time','Full-time','Over-time'])
#Reason: This feature helps the model as it captures the work Intensity.

In [19]:
print(df[['hours_per_week', 'hours_category']].head(10))

   hours_per_week hours_category
0              40      Full-time
1              13      Part-time
2              40      Full-time
3              40      Full-time
4              40      Full-time
5              40      Full-time
6              16      Part-time
7              45      Over-time
8              50      Over-time
9              40      Full-time

In [31]:
# Log Transformation 
import numpy as np

# Fill missing values first
df['capital_gain'] = df['capital_gain'].fillna(0)

# Log transform using numpy
df['capital_gain'] = np.log1p(df['capital_gain'])

# Check output
print(df[['capital_gain']].head())

   capital_gain
0      7.684784
1      0.000000
2      0.000000
3      0.000000
4      0.000000

Why! 
1. Data is skewed 
2. Large values normalize

In [53]:
#Feature Selection 
from sklearn.ensemble import IsolationForest

numeric_columns = df.select_dtypes(include=['int64','float64']).columns

iso = IsolationForest(contamination=0.01, random_state=42)
outliers = iso.fit_predict(df[numeric_columns])

# Keep only non-outliers
df_clean = df[outliers == 1]

print("Original shape:", df.shape)
print("Shape after removing outliers:", df_clean.shape)

Original shape: (32561, 23)
Shape after removing outliers: (32235, 23)

In [55]:
!pip install ppscore

Collecting ppscore
  Downloading ppscore-1.3.1.tar.gz (17 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: pandas>=1.0.0 in c:\users\vinod\anaconda3\lib\site-packages (from ppscore) (2.3.3)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in c:\users\vinod\anaconda3\lib\site-packages (from ppscore) (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\vinod\anaconda3\lib\site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\vinod\anaconda3\lib\site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\vinod\anaconda3\lib\site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\vinod\anaconda3\lib\site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vinod\anaconda3\lib\site-packages (from pandas>=1.0.0->ppscore) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vinod\anaconda3\lib\site-packages (from pandas>=1.0.0->ppscore) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vinod\anaconda3\lib\site-packages (from pandas>=1.0.0->ppscore) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vinod\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ppscore) (1.17.0)
Building wheels for collected packages: ppscore
  Building wheel for ppscore (pyproject.toml): started
  Building wheel for ppscore (pyproject.toml): finished with status 'done'
  Created wheel for ppscore: filename=ppscore-1.3.1-py2.py3-none-any.whl size=13262 sha256=49709ed0b1899e35bf51fd684c1d56c5ce59b6bfda48c7ce796c55baf274e937
  Stored in directory: c:\users\vinod\appdata\local\pip\cache\wheels\b4\95\1f\bfb3b7b3845232909c01caa738277f86d0148164d3a617ad42
Successfully built ppscore
Installing collected packages: ppscore
Successfully installed ppscore-1.3.1

In [56]:
#PPs score (predictive power score)
import ppscore as pps

pps_matrix = pps.matrix(df)
print(pps_matrix[['x','y','ppscore']])

                  x               y   ppscore
0               age             age  1.000000
1               age       workclass  0.000000
2               age          fnlwgt  0.000000
3               age       education  0.000000
4               age   education_num  0.000000
..              ...             ...       ...
524  hours_category       sex_ Male  0.000000
525  hours_category   income_ <=50K  0.000000
526  hours_category    income_ >50K  0.000000
527  hours_category       age_group  0.150419
528  hours_category  hours_category  1.000000

[529 rows x 3 columns]

Why !
1.Using PPS score we can see how much effects a feature has on the target variable.

## Final Conclusion in this Assignment ##
• Missing values properly handled
• Scaling improves model performance
• Encoding converts categorical to numerical
• Feature engineering improves prediction
• PPS & Isolation Forest help in feature selection

In [ ]:
Complete The Assignment No - 9